### ISSUE TITLE
ModuleNotFoundError: No module named 'func'

### ISSUE THREAD

**Issue by asifehmad** [mrradist/nqr_detector#1]
Hi,
While running the `TNT_detector.py` file I am coming across the error:

![Error](https://user-images.githubusercontent.com/54246513/164130475-a572513c-2b5d-46a1-82e2-1eef4ecad322.PNG)
Could you please check it?
I am running the file in Google Colab.
Thanks in anticipation.

**Comment by sinc** [comment]
Try replace this line by
`import functions as func`

**Comment by asifehmad** [comment]
> Try replace this line by `import functions as func`

Yes! It worked that way. Thanks a lot.
